### ISSUE TITLE
Can you help me fix this problem?

### ISSUE THREAD

**Issue by OaDsis** [sczhengyabin/Image-Downloader#17]
[09:57:20]   -e Baidu -n 100 -j 4 -o "./download_images/rain" -S  "rain"
[09:57:20]  Scraping From Baidu Image Search ...
[09:57:20]  Keywords:  rain
[09:57:20]  Number:  100
[09:57:20]  Face Only:  False
[09:57:20]  Safe Mode:  True
[09:57:20]  Query URL:  https://image.baidu.com/search/index?tn=baiduimage&word=rain
[09:57:24]  Exception in thread Thread-4:
[09:57:24]  Traceback (most recent call last):
[09:57:24]    File "threading.py", line 914, in _bootstrap_inner
[09:57:24]    File "threading.py", line 862, in run
[09:57:24]    File "Image-Downloader-master\image_downloader.py", line 52, in main
[09:57:24]    File "Image-Downloader-master\crawler.py", line 254, in crawl_image_urls
[09:57:24]    File "site-packages\selenium\webdriver\phantomjs\webdriver.py", line 52, in __init__
[09:57:24]    File "site-packages\selenium\webdriver\common\service.py", line 96, in start
[09:57:24]    File "site-packages\selenium\webdriver\common\service.py", line 109, in assert_process_still_running
[09:57:24]  selenium.common.exceptions.WebDriverException: Message: Service C:\Users\wyy\AppData\Local\Temp\_MEI145722/bin/phantomjs.exe unexpectedly exited. Status code was: 4294967295
[09:57:25]  stopped

**Comment by OaDsis** [comment]
This problem was caused by downloading ‘phantomjs-2.5.0-beta2-windows.zip’, and it was fixed by downloading ‘phantomjs-2.1.1-windows’
