### ISSUE TITLE
按照指导进行安装后搜索龙猫，不论baidu还是bing都是如此'Service' object has no attribute 'process'

### ISSUE THREAD

**Issue by luckhhn** [sczhengyabin/Image-Downloader#21]
您好，谢谢。

GUI输出的结果如下：

[17:40:19]   -e Google -n 20 -j 50 -o "./download_images/龙猫" -S  "龙猫"
[17:40:19]  Scraping From Google Image Search ...
[17:40:19]  Keywords:  龙猫
[17:40:19]  Number:  20
[17:40:19]  Face Only:  False
[17:40:19]  Safe Mode:  True
[17:40:19]  Query URL:  https://www.google.com/search?tbm=isch&hl=en&q=%E9%BE%99%E7%8C%AB&safe=on
[17:40:19]  Exception in thread Thread-7:
[17:40:19]  Traceback (most recent call last):
[17:40:19]    File "threading.py", line 914, in _bootstrap_inner
[17:40:19]    File "threading.py", line 862, in run
[17:40:19]    File "Image-Downloader-master\image_downloader.py", line 52, in main
[17:40:19]    File "Image-Downloader-master\crawler.py", line 254, in crawl_image_urls
[17:40:19]    File "site-packages\selenium\webdriver\phantomjs\webdriver.py", line 52, in __init__
[17:40:19]    File "site-packages\selenium\webdriver\common\service.py", line 74, in start
[17:40:19]    File "subprocess.py", line 640, in __init__
[17:40:19]    File "subprocess.py", line 848, in _get_handles
[17:40:19]  OSError: [WinError 6] 句柄无效。
[17:40:19]  Exception ignored in: 
[17:40:19]  <bound method Service.__del__ of <selenium.webdriver.phantomjs.service.Service object at 0x000002335A2F50F0>>
[17:40:19]  Traceback (most recent call last):
[17:40:19]    File "site-packages\selenium\webdriver\common\service.py", line 173, in __del__
[17:40:19]    File "site-packages\selenium\webdriver\common\service.py", line 145, in stop
[17:40:19]  AttributeError
[17:40:19]  : 
[17:40:19]  'Service' object has no attribute 'process'
[17:40:20]  stopped

搜了很多解决办法，没有用，所以来提问，也希望得到解决指导，可以帮助到其他也遇到我这样问题的朋友

**Comment by luckhhn** [comment]
用image_downloader_gui.exe 会出现上述问题，但是用命令行运行然后就不会，奇怪

**Comment by sczhengyabin** [comment]
@luckhhn 无法复现，试试最新的提交的代码

**Comment by rookiexiao123** [comment]
我刚才也遇到了这样的问题，主要是因为没有适配的chromedriver.exe文件。如何找对应，请看https://blog.csdn.net/weixin_44545954/article/details/86690861。下载之后放在Python\Python36\Scripts，再次执行就ok 了
