### ISSUE TITLE
Exception in thread Thread-1

### ISSUE THREAD

**Issue by yran1011** [sczhengyabin/Image-Downloader#31]
[18:33:35]   -e Baidu -d chrome_headless -n 100 -j 50 -o "./download_images/dog" -S  "dog"
[18:33:35]  Scraping From Baidu Image Search ...
[18:33:35]  Keywords:  dog
[18:33:35]  Number:  100
[18:33:35]  Face Only:  False
[18:33:35]  Safe Mode:  True
[18:33:35]  Query URL:  https://image.baidu.com/search/index?tn=baiduimage&word=dog
[18:33:38]  Exception in thread Thread-1:
[18:33:38]  Traceback (most recent call last):
[18:33:38]    File "/home/yuran/anaconda3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
[18:33:38]      self.run()
[18:33:38]    File "/home/yuran/anaconda3/lib/python3.7/threading.py", line 865, in run
[18:33:38]      self._target(*self._args, **self._kwargs)
[18:33:38]    File "/home/yuran/project/Image-Downloader/image_downloader.py", line 54, in main
[18:33:38]      browser=args.driver)
[18:33:38]    File "/home/yuran/project/Image-Downloader/crawler.py", line 315, in crawl_image_urls
[18:33:38]      proxy=proxy, proxy_type=proxy_type)
[18:33:38]    File "/home/yuran/project/Image-Downloader/crawler.py", line 195, in baidu_get_image_url_using_api
[18:33:38]      res = requests.get(init_url, proxies=proxies)
[18:33:38]    File "/home/yuran/anaconda3/lib/python3.7/site-packages/requests/api.py", line 75, in get
[18:33:38]      return request('get', url, params=params, **kwargs)
[18:33:38]    File "/home/yuran/anaconda3/lib/python3.7/site-packages/requests/api.py", line 60, in request
[18:33:38]      return session.request(method=method, url=url, **kwargs)
[18:33:38]    File "/home/yuran/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
[18:33:38]      resp = self.send(prep, **send_kwargs)
[18:33:38]    File "/home/yuran/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 668, in send
[18:33:38]      history = [resp for resp in gen] if allow_redirects else []
[18:33:38]    File "/home/yuran/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 668, in <listcomp>
[18:33:38]      history = [resp for resp in gen] if allow_redirects else []
[18:33:38]    File "/home/yuran/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 165, in resolve_redirects
[18:33:38]      raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects, response=resp)
[18:33:38]  requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
[18:33:38]  stopped
这是什么问题呢?

**Comment by sczhengyabin** [comment]
已修复
7013bfdceb78c1d7ad52da9e17b9b361811c389a
