### ISSUE TITLE
hi~我是一个正在学习ai的学生，使用您的爬虫爬取baidu图片，特此求助：使用gui方式打开，选取baidu，搜索关键字，点击start，然后就会报错武侠

### ISSUE THREAD

**Issue by healthybaobao** [sczhengyabin/Image-Downloader#36]
[10:07:57]   -e Baidu -d chrome_headless -n 100 -j 50 -o "E:/zb/code/images/mouse" -S  "mouse"
[10:07:57]  Scraping From Baidu Image Search ...
[10:07:57]  Keywords:  mouse
[10:07:57]  Number:  100
[10:07:57]  Face Only:  False
[10:07:57]  Safe Mode:  True
[10:07:57]  Query URL:  https://image.baidu.com/search/index?tn=baiduimage&word=mouse
[10:07:57]  Exception in thread 
[10:07:57]  Thread-3
[10:07:57]  :
[10:07:57]  Traceback (most recent call last):
[10:07:57]    File "D:\软件\python64\lib\threading.py", line 954, in _bootstrap_inner
[10:07:57]  self.run()
[10:07:57]    File "D:\软件\python64\lib\threading.py", line 892, in run
[10:07:57]  self._target(*self._args, **self._kwargs)
[10:07:57]    File "E:\zb\code\Image-Downloader\image_downloader.py", line 50, in main
[10:07:57]  crawled_urls = crawler.crawl_image_urls(args.keywords,
[10:07:57]    File "E:\zb\code\Image-Downloader\crawler.py", line 325, in crawl_image_urls
[10:07:57]  image_urls = baidu_get_image_url_using_api(keywords, max_number=max_number, face_only=face_only,
[10:07:57]    File "E:\zb\code\Image-Downloader\crawler.py", line 206, in baidu_get_image_url_using_api
[10:07:57]  init_json = json.loads(res.text.replace(r"\'", ""), encoding='utf-8', strict=False)
[10:07:57]    File "D:\软件\python64\lib\json\__init__.py", line 359, in loads
[10:07:57]  return cls(**kw).decode(s)
[10:07:57]  TypeError
[10:07:57]  : 
[10:07:57]  __init__() got an unexpected keyword argument 'encoding'
[10:07:57]  stopped

**Comment by Ans0nXD** [comment]
https://www.pianshen.com/article/59561646121/ 试一试能否有用

**Comment by zsr228** [comment]
change
init_json = json.loads(res.text.replace(r"\'", ""), encoding='utf-8', strict=False)
to
init_json = json.loads(res.text.replace(r"\'", ""))

**Comment by Lininggggggg** [comment]
改了之后，还是不行啊

**Comment by Lininggggggg** [comment]
找到问题了，要改两处
![image](https://user-images.githubusercontent.com/52039865/145751356-6a667bc1-dba0-4953-9a7b-26fd8f247256.png)

**Comment by zszaxlywn** [comment]
[22:31:44]   -e Baidu -d chrome -n 100 -j 50 -o "./download_images/龙猫" -S  "龙猫"
[22:31:44]  Scraping From Baidu Image Search ...
[22:31:44]  Keywords:  龙猫
[22:31:44]  Number:  100
[22:31:44]  Face Only:  False
[22:31:44]  Safe Mode:  True
[22:31:44]  https://image.baidu.com/search/index?tn=baiduimage&word=%E9%BE%99%E7%8C%AB
[22:31:44]  Query URL:  https://image.baidu.com/search/index?tn=baiduimage&word=%E9%BE%99%E7%8C%AB
[22:31:44]  __init__() got an unexpected keyword argument 'encoding'
[22:31:44]  __init__() got an unexpected keyword argument 'encoding'
[22:31:44]  __init__() got an unexpected keyword argument 'encoding'
[22:31:44]  __init__() got an unexpected keyword argument 'encoding'
[22:31:44]  __init__() got an unexpected keyword argument 'encoding'
[22:31:44]  __init__() got an unexpected keyword argument 'encoding'
[22:31:44]  __init__() got an unexpected keyword argument 'encoding'
[22:31:44]  == 0 out of 0 crawled images urls will be used.
[22:31:44]  Finished.
[22:31:45]  stopped

**Comment by zszaxlywn** [comment]
> 找到问题了，要改两处![image](https://user-images.githubusercontent.com/52039865/145751356-6a667bc1-dba0-4953-9a7b-26fd8f247256.png)

您好，能帮我看一下是什么问题吗

**Comment by zszaxlywn** [comment]
按照你这个改的，没改之前我最上面那个问题一样

**Comment by Zhangbole1** [comment]
ty!

**Comment by Zhangbole1** [comment]
ty!

**Comment by Oneboy77** [comment]
ok,thank
