### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by JJHACKER** [sczhengyabin/Image-Downloader#72]
[19:43:31]   -e Google -d chrome_headless -n 100 -j 50 -o "./download_images/jj" -S  "jj"
[19:43:31]  Checking Google Chrome and chromedriver ...
[19:43:32]  Exception in thread 
[19:43:32]  Thread-1 (main)
[19:43:32]  :
[19:43:32]  Traceback (most recent call last):
[19:43:32]    File "threading.py", line 1016, in _bootstrap_inner
[19:43:32]    File "threading.py", line 953, in run
[19:43:32]    File "image_downloader.py", line 59, in main
[19:43:32]    File "utils.py", line 75, in resolve_dependencies
[19:43:32]    File "chromedriver_autoinstaller\__init__.py", line 21, in install
[19:43:32]    File "chromedriver_autoinstaller\utils.py", line 207, in download_chromedriver
[19:43:32]    File "chromedriver_autoinstaller\utils.py", line 172, in get_matched_chromedriver_version
[19:43:32]    File "urllib\request.py", line 216, in urlopen
[19:43:32]    File "urllib\request.py", line 525, in open
[19:43:32]    File "urllib\request.py", line 634, in http_response
[19:43:32]    File "urllib\request.py", line 563, in error
[19:43:32]    File "urllib\request.py", line 496, in _call_chain
[19:43:32]    File "urllib\request.py", line 643, in http_error_default
[19:43:32]  urllib.error
[19:43:32]  .
[19:43:32]  HTTPError
[19:43:32]  : 
[19:43:32]  HTTP Error 403: Forbidden
[19:43:32]  stopped

===========
bing api working fine.
windows 10

**Comment by CharlesPikachu** [comment]
try: https://github.com/CharlesPikachu/imagedl/tree/main
